name: RestoreNature
main: io.github.kuohsuanlo.restorenature.RestoreNaturePlugin
version: ${version}
commands:
  restorenature:
    description: .
    usage: 
permissions:
    restorenature.*:
        description: Gives access to all restorenature commands
        children:
            restorenature.manualrestore: true
    restorenature.mr:
        description: manually force the plugin to restore the chunk player standing in.
        default: op
    restorenature.rnworld:
        description: manually make all the chunks exceeds the max untouched time and start to resotre the world(still according to the config).
        default: op
    restorenature.trymr:
        description: try to restore the land, if not success, show why.
        default: op