name: RestoreNature
main: io.github.kuohsuanlo.restorenature.RestoreNaturePlugin
version: ${version}
depend: [Factions]
commands:
  restorenature:
    description: .
    usage: 
  reload:
    description: .
    usage: 
permissions:
    restorenature.*:
        description: Gives access to all restorenature commands
        children:
            restorenature.manualrestore: true
    restorenature.manualrestore:
        description: manually force the plugin to restore the chunk player standing in.
        default: op
    restorenature.reload:
        description: reload the plugin's config.
        default: op