name: RestoreNature
main: io.github.kuohsuanlo.restorenature.RestoreNaturePlugin
version: ${version}
depend: [Factions]
commands:
  restorenature:
    description: .
    usage: 
permissions:
    restorenature.*:
        description: Gives access to all restorenature commands
        children:
            restorenature.manualrestore: true
    restorenature.manualrestore:
        description: check falloutcraft status.
        default: op